- name: playper variable
  hosts: local
  connection: local

  vars:
    NUMBEROFVAR: "DEVSEC CONTENT"
    NUMBEROFSESSION: 15
    LIVE: true
    VALUES: "JAVA,C,DEVOPS"

  tasks:
    - name: print play per variable
      ansible.builtin.debug:
        msg: |
          NUMBEROFVAR: "{{ NUMBEROFVAR }}"
          NUMBEROFSESSION: "{{ NUMBEROFSESSION }}"
          LIVE: "{{ LIVE }}"
          VALUES: "{{ VALUES }}"
    