- name: "playper varaible" 
  hosts: local
  connection: local
  vars:
    NUMBEROFVAR: "DEVSEC CONTENT"
    NUMBEROFSESSION: 15
    LIVE: true
    VALUES: "JAVA,ANSIBLE,LINUX"
  tasks:
    - name: print play per varaible
      ansible.builtin.debug:
         msg: |
           NUMBEROFVAR: "{{ NUMBEROFVAR }}"
           NUMBEROFSESSION: "{{ NUMBEROFSESSION }}"
           LIVE: "{{ LIVE }}"
           VALUES: "{{ VALUES }}"

