- name: "playper varaible" 
  hosts: local
  connection: local
  vars:
   NUMBEROFVAR: "DEVSEC CONTENT"
   NUMBEROFSESSION: 15
   IS_LIVE: true
   VALUES: "JAVA,C,DEVOPS"
  tasks:
  - name: print play per varaible
    ansible.builtin.debug:
      msg: |
      NUMBEROFVAR: "{{ NUMBEROFVAR }}"
      NUMBEROFSESSION: "{{ NUMBEROFSESSION }}"
      IS-LIVE: "{{ IS-LIVE }}"
      VALUES: "{{ VALUES }}"
    