- name: practice
  hosts: local
  connection: local
  vars:
    COURSE: "JAVA"
    DURATION: 45
  tasks:
    - name: print the another example
      ansible.builtin.debug:
        msg: |
          COURSE: {{ COURSE }}
          DURATION: {{ DURATION }}