- name: practice
  hosts: local
  connection: local
  file_vars:
    filesread.yml
  tasks:
    - name: print the another example
      ansible.builtin.debug:
        msg: "course is: {{ COURSE }} duration is: {{ DURATION }}"