- name: playbook variable perference
  hosts: local
  connection: local
  vars:
    name: "ansible from play"
  vars_files:
    filesread.yml
  vars_prompt:
    name: NAME
    prompt: "please enter prompt"
    private: no
  tasks:
    - name: print the ansible varable perfermance
      vars:
        name: "ansible  from tasks"
      ansible.builtin.debug:
        msg: "{{ name }}"