- name: condition with ansible
  hosts: local
  connection: local
  vars:
    SESSION: 7
  tasks:
    - name: print the greter then 5 sessons
      ansible.builtin.debug:
        msg: "yes, Seesiion is Greater then 5: {{ SESSION }}"
      when: SESSION > 7
