- name: loop conditions
  hosts: local
  connection: local
  
  tasks:
    - name: for looping conditions
      ansible.builtin.debug:
        msg: "{{ name }}"
      loop:
       -RAMESH
       -RAVI
       -DIVYA
