- name: "Ravi Dasari"
  DOB: "1990-01-01"
  mobileNumber: 123456
  addresses: 
  - flatNumber: 104
    street: "gandhi nagar"
    city: hydrabad
    type: current

  - flatNumber: 104
    street: "gandhi nagar"
    city: "hydrabad"
    type: perm

- name: "Divya Dasari"
  DOB: "2000-01-01"
  mobileNumber: 456771
  addresses: 
  - flatNumber: 104
    street: "gandhi nagar"
    city: bangalore
    type: current

  - flatNumber: 104
    street: "gandhi nagar"
    city: bangalore
    type: perm