- name: task level variables
  hosts:  local
  connection: local
  vars_files:
  - 17-playbook.yml  
  tasks:  
  - name: task level variables
    vars: 
      TRAINER:  "Siva Kumar Reddy"
    ansible.builtin.debug:
      msg:  "course is: {{ COURSE }}, duration is: {{ DURATION }}, trainer is: {{ TRAINER }}"