- name: demo on data types
  hosts:  local
  connection: local
  vars: 
    PROGRAM:  "DevSecOPs with AWS"
    DURATION: 140
    IS_LIVE:  true
    DETAIALS: 
      MONTHS: 4
      TRAINER:  "Siva Kumar Reddy"
    TOPICS: 
    - Linux
    - Shell
    - Ansible
  tasks:  
  - name: print varibles
    ansible.builtin.debug: 
      msg: |
        Program:  {{ PROGRAM }}
        DURATION: {{ DURATION }}
        IS_LIVE: {{ IS_LIVE }}
        DETAIALS: {{ DETAIALS }}
        TOPICS: {{ TOPICS }}