- name: data type variable
  hosts:  local
  connection: local
  vars: 
    COURSE: "Ravi Dasari"
    DURATION: "140 rs"
    DETAIALS: 
      MONTHS: 4
      TRAINER:  "Ravi Dasari"
    TOPICS: 
    - Linux
    - Shell
    - Ansible
    - Docker
    SALARY:
    - 50000
    - 60000
    - 70000
  tasks:  
  - name: data type varibles
    ansible.builtin.debug:  
      msg: |
      Course: "{{  COURSE }}"
      duration: "{{ DURATION }}"
      details: "{{ DETAIALS }}"
      topics: "{{ TOPICS }}"
      salaries: "{{ SALARY }}"
  