- name: condition
  hosts:  local
  connection: local
  vars: 
    AVARAGE:  5
  tasks:  
  - name: condition for the loop
    ansible.builtin.debug:
      msg: "Yes, more than 5 sessions"
    when: AVARAGE > 6