- name: gathering facts
  hosts:  local
  connection: local
  tasks:
  - name: print facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"
  - name: check redhart or not
    ansible.builtin.debug:
     msg: "Yes, package manager is RedHat"
    when: ansible_facts.os_family == "RedHat"
  - name: check redhart or not
    ansible.builtin.debug:
     msg: "Yes, package manager is Dibian"
    when: ansible_facts.os_family == "Debian"

  - name: copy folder
    ansible.builtin.copy:
      src:  D:\shell-roboshop
      dest: C:\Downloads
  
  - name:  run and install package
    ansible.builtin.dnf:
      name: nginx
      state:  present
    
