- name: ansible command vs shell module
  hosts: local
  connection: local
  become: yes
  tasks: 
  - name: command module test
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: user_output
  
  - name: print output
    ansible.builtin.debug:
      msg: "{{ user_output }}"

  - name: run command
    ansible.builtin.dnf:
      name:  nginx
      state: present
  - name: copy from direction
    ansible.builtin.copy: 
      src:  D:\shell-practice
      dest: D:\shell-roboshop

