- name: Hello World
  hosts:  local
  connection: local
  tasks: 
  - name: print hello World
    ansible.builtin.debug:  
      msg:  " Hello World "

- name: play 2
  hosts:  local
  connection: local
  tasks: 
  - name: print playbook 2 hello World
    ansible.builtin.debug:  
      msg:  " hello world print playbook 2 "
